<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit36afdd62bb083aa085d4a00d4a40e087
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Sensei_Courses_For_BBPress\\' => 27,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Sensei_Courses_For_BBPress\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/includes/classes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit36afdd62bb083aa085d4a00d4a40e087::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit36afdd62bb083aa085d4a00d4a40e087::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit36afdd62bb083aa085d4a00d4a40e087::$classMap;

        }, null, ClassLoader::class);
    }
}
